def menu():
    '''Cria o menu da aplicação'''
    print('=>               MENU                <=')
    print('#' * 39)
    print('## 1 - Pagar Conta                   ##')
    print('## 2 - Receber Conta                 ##')
    print('## 3 - Ver Saldo                     ##')
    print('## 4 - Ver última conta              ##')
    print('## 5 - Comprovar conta por descrição ##')
    print('## 6 - Apagar conta                  ##')
    print('## 7 - Ver todas as contas           ##')
    print('## 8 - Relatório de contas a pagar   ##')
    print('## 9 - Relatório de contas a receber ##')
    print('## 0 - Sair                          ##')
    print('#' * 39)
    print("OBS: Não use acentos gráficos")